# Generated by Django 6.0.2 on 2026-02-18 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='energy.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='energy.user'),
            preserve_default=False,
        ),
    ]
