# Generated by Django 6.0.2 on 2026-02-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0002_alert_category_alert_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consommation',
            name='price',
        ),
        migrations.AddField(
            model_name='consommation',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=12),
            preserve_default=False,
        ),
    ]
