# Generated by Django 6.0.2 on 2026-02-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0003_remove_consommation_price_consommation_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(default='alert', max_length=30),
        ),
    ]
